version: '3'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/restaurant_app
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_EXPIRE=30d
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run server

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    command: npm start

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: